apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: nfs-mounter
spec:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 100%
  template:
    metadata:
      name: nfs-mounter
      labels:
        app: nfs-mounter
    spec:
      hostPID: true
      # Temporarily, I think in production we want to give this more time to exit!
      terminationGracePeriodSeconds: 0
      containers:
        - image:  gcr.io/data8x-scratch/nfs-mounter:v7
          name: nfs-mounter
          env:
          # These two variables changing will restart all the daemonset pods
          - name: FILESERVERS
            value: {{ toJson .Values.nfsMounter.fileservers | quote }}
          - name: MOUNT_PATH_TEMPLATE
            value: {{ .Values.nfsMounter.mountPathTemplate | quote }}
          securityContext:
            privileged: true
          workingDir: /srv/script
          securityContext:
              privileged: true
