version: "v0.6.0"

rbac:
  enabled: true

hub:
  extraConfig: |
    from kubespawner import KubeSpawner
    from tornado import gen
    import yaml

    class CustomKubeSpawner(KubeSpawner):
      @gen.coroutine
      def start(self):
        with open('/etc/jupyterhub/config/custom.memory') as f:
          custom_attr_lists = yaml.safe_load(f)
          for attr, users in custom_attr_lists.items():
            if self.user.name in users:
              self.mem_limit = attr
              self.mem_guarantee = attr
              break

        return (yield super().start())
    c.JupyterHub.spawner_class = CustomKubeSpawner

cull:
  enabled: true
  timeout: 3600 # default

auth:
  type: google
  admin:
    users:
      # infrastructure
      - rylo
      - yuvipanda
      # su18 data8 instructors
      - deborah_nolan
      - vinitra
      - fhdkmrn
      # sp18 prob140 GSIs

singleuser:
  memory:
    guarantee: 1G
    limit: 1G
  storage:
    type: hostPath
    extraVolumes:
      - name: home
        hostPath:
          path: /mnt/homes/{username}
    extraVolumeMounts:
      - name: home
        mountPath: /home/jovyan
  schedulerStrategy: pack
  image:
    name: "gcr.io/smooth-calling-205216/singleuser-summer"
